/**
 * Theme object and TypeScript types for design tokens
 *
 * This file provides typed access to all design tokens generated by Style Dictionary.
 * Use the exported types (ColorToken, SpacingToken, etc.) in component props to ensure
 * only valid token keys are accepted.
 *
 * @example
 * ```tsx
 * import { ColorToken } from './theme';
 *
 * interface IconProps {
 *   color?: ColorToken; // Only accepts valid color token keys
 * }
 *
 * // Valid:
 * <Icon color="colorRed500" />
 *
 * // TypeScript error:
 * <Icon color="#ff0000" />
 * ```
 */

import * as tokens from '../dist/tokens/generated.js';

// Re-export all tokens
export * from '../dist/tokens/generated.js';

// Create theme object with grouped tokens
export const theme = {
  // Color tokens
  color: Object.fromEntries(
    Object.entries(tokens).filter(([key]) => key.startsWith('Color'))
  ),

  // Spacing tokens
  spacing: Object.fromEntries(
    Object.entries(tokens).filter(([key]) => key.startsWith('Spacing'))
  ),

  // Font tokens
  font: Object.fromEntries(
    Object.entries(tokens).filter(([key]) => key.startsWith('Font'))
  ),

  // Line height tokens
  line: Object.fromEntries(
    Object.entries(tokens).filter(([key]) => key.startsWith('Line'))
  ),

  // Letter spacing tokens
  letter: Object.fromEntries(
    Object.entries(tokens).filter(([key]) => key.startsWith('Letter'))
  ),

  // Radii tokens
  radii: Object.fromEntries(
    Object.entries(tokens).filter(([key]) => key.startsWith('Radii'))
  ),

  // Shadow tokens
  shadow: Object.fromEntries(
    Object.entries(tokens).filter(([key]) => key.startsWith('Shadow'))
  ),
} as const;

// TypeScript types
export type Theme = typeof theme;

// Token type unions for component props
export type ColorToken = keyof typeof theme.color;
export type SpacingToken = keyof typeof theme.spacing;
export type FontFamilyToken = keyof typeof theme.font;
export type LineHeightToken = keyof typeof theme.line;
export type LetterSpacingToken = keyof typeof theme.letter;
export type RadiiToken = keyof typeof theme.radii;
export type ShadowToken = keyof typeof theme.shadow;

// Combined token types
export type TypographyToken = FontFamilyToken | LineHeightToken | LetterSpacingToken;
