/* `dsbridge rules` — the same rules, as prose.
 *
 * This is the half an agent reads. `dsbridge check` tells it a line is wrong;
 * this tells it what the rule is protecting, so it can fix the cause rather
 * than silence the finding. Both come off the same objects, so guidance the
 * tool does not enforce, and enforcement nobody explained, are both impossible.
 */
import { RULES } from "../rules/index.js";
import { isEnforced } from "../rules/types.js";
import type { Reads, Rule, Target } from "../rules/types.js";
import { bold, dim } from "../text.js";

export type RulesOptions = {
  /** One rule, in full. */
  id?: string;
  target?: Target;
  /** Markdown, for pasting into an agent's instructions. */
  markdown?: boolean;
  color?: boolean;
};

const wrap = (text: string, width: number, indent: string) => {
  const out: string[] = [];
  let line = "";
  for (const word of text.split(/\s+/)) {
    if (line.length + word.length + 1 > width) {
      out.push(indent + line);
      line = word;
    } else line = line === "" ? word : `${line} ${word}`;
  }
  if (line !== "") out.push(indent + line);
  return out.join("\n");
};

/** What kind of thing a path is, as far as any rule is concerned. */
export const readsOf = (file: string): Reads | undefined => {
  if (/\.(?:css|scss|sass|less)$/.test(file)) return "stylesheet";
  if (/\.(?:tsx|ts|jsx|js|mjs|cjs)$/.test(file)) return "component";
  return undefined;
};

/**
 * The rules that have anything to say about one file.
 *
 * The whole set is 22 KB and most of it is about something else. An agent
 * about to edit a stylesheet needs the four rules about stylesheets, now,
 * rather than a document it will skim.
 */
export function rulesForFile(file: string, target?: Target): Rule[] {
  const reads = readsOf(file);
  if (reads === undefined) return [];
  return selectRules({ ...(target !== undefined ? { target } : {}) }).filter((rule) => rule.reads === reads);
}

export const selectRules = (options: RulesOptions = {}): Rule[] =>
  RULES.filter((rule) => options.id === undefined || rule.id === options.id).filter(
    (rule) => options.target === undefined || rule.target === options.target || rule.target === "both",
  );

/** A rule as data. `enforced` is the derived half of the model — without it a
    reader cannot tell a finding it will be shown from an argument it has to
    weigh — and the functions are dropped because JSON cannot carry them. */
export type RuleData = Omit<Rule, "check" | "needs"> & { enforced: boolean };

export const ruleData = (rules: Rule[]): RuleData[] =>
  rules.map((rule) => ({
    id: rule.id,
    title: rule.title,
    why: rule.why,
    instead: rule.instead,
    target: rule.target,
    reads: rule.reads,
    enforced: isEnforced(rule),
  }));

export const rulesAsJson = (options: RulesOptions = {}): RuleData[] => ruleData(selectRules(options));

const section = (rules: Rule[]) =>
  rules.flatMap((rule) => [
    `### ${rule.id}`,
    "",
    `**${rule.title}** *(${rule.target})*`,
    "",
    rule.why,
    "",
    `**Instead.** ${rule.instead}`,
    "",
  ]);

const asMarkdown = (rules: Rule[]) => {
  const enforced = rules.filter(isEnforced);
  const advisory = rules.filter((rule) => !isEnforced(rule));
  return [
    "# Design system rules",
    "",
    "Generated by `dsbridge rules --markdown`. The reasoning is what to weigh when a",
    "rule and a design disagree, not a script to recite. A finding you cannot fix",
    "without breaking the design is a finding worth arguing with — in the pull",
    "request, not in a config.",
    "",
    "## Checked",
    "",
    "`dsbridge check` proves these. A violation is a fact, not an opinion.",
    "",
    ...section(enforced),
    "## Judgement",
    "",
    "No tool can prove these. They are the calls someone has to make with the",
    "codebase in front of them, and they matter more than the checked ones — a repo",
    "can pass every check above and still be a design system in name only.",
    "",
    ...section(advisory),
  ].join("\n");
};

export function renderRules(chosen: Rule[], options: RulesOptions = {}): string {
  if (chosen.length === 0) {
    return options.id !== undefined
      ? `no rule called "${options.id}" — dsbridge rules lists them all\n`
      : "no rule reads this kind of file\n";
  }
  if (options.markdown === true) return asMarkdown(chosen);

  const color = options.color ?? true;
  if (chosen.length === 1 || options.id !== undefined) {
    return chosen
      .map((rule) =>
        [
          `${bold(rule.id, color)}  ${dim(`${rule.target}, ${isEnforced(rule) ? "checked" : "judgement"}`, color)}`,
          "",
          wrap(rule.title, 78, "  "),
          "",
          wrap(rule.why, 78, "  "),
          "",
          wrap(`Instead: ${rule.instead}`, 78, "  "),
          "",
        ].join("\n"),
      )
      .join("\n");
  }

  const width = Math.max(...chosen.map((rule) => rule.id.length));
  return (
    chosen
      .map(
        (rule) =>
          `  ${bold(rule.id.padEnd(width), color)}  ${rule.title} ${dim(
            `(${rule.target}${isEnforced(rule) ? "" : ", judgement"})`,
            color,
          )}`,
      )
      .join("\n") +
    `\n\n${dim(`dsbridge rules ${chosen[0]!.id} for the reasoning, --markdown for all of it`, color)}\n`
  );
}
