/* `mds rules` — the same rules, as prose.
 *
 * This is the half an agent reads. `mds check` tells it a line is wrong;
 * this tells it what the rule is protecting, so it can fix the cause rather
 * than silence the finding. Both come off the same objects, so guidance the
 * tool does not enforce, and enforcement nobody explained, are both impossible.
 */
import { RULES } from "../rules/index.js";
import type { Rule, Target } from "../rules/types.js";

export type RulesOptions = {
  /** One rule, in full. */
  id?: string;
  target?: Target;
  /** Markdown, for pasting into an agent's instructions. */
  markdown?: boolean;
  color?: boolean;
};

const ESC = "\u001b[";
const dim = (s: string, on: boolean) => (on ? `${ESC}2m${s}${ESC}0m` : s);
const bold = (s: string, on: boolean) => (on ? `${ESC}1m${s}${ESC}0m` : s);

const wrap = (text: string, width: number, indent: string) => {
  const out: string[] = [];
  let line = "";
  for (const word of text.split(/\s+/)) {
    if (line.length + word.length + 1 > width) {
      out.push(indent + line);
      line = word;
    } else line = line === "" ? word : `${line} ${word}`;
  }
  if (line !== "") out.push(indent + line);
  return out.join("\n");
};

export const selectRules = (options: RulesOptions = {}): Rule[] =>
  RULES.filter((rule) => options.id === undefined || rule.id === options.id).filter(
    (rule) => options.target === undefined || rule.target === options.target || rule.target === "both",
  );

const asMarkdown = (rules: Rule[]) =>
  [
    "# Mond Design System — rules",
    "",
    "Generated by `mds rules --markdown`. Every rule here is checked by `mds check`;",
    "the reasoning is what to weigh when a rule and a design disagree, not a script",
    "to recite. A finding you cannot fix without breaking the design is a finding",
    "worth arguing with — in the pull request, not in a config.",
    "",
    ...rules.flatMap((rule) => [
      `## ${rule.id}`,
      "",
      `**${rule.title}** *(${rule.target})*`,
      "",
      rule.why,
      "",
      `**Instead.** ${rule.instead}`,
      "",
    ]),
  ].join("\n");

export function renderRules(options: RulesOptions = {}): string {
  const chosen = selectRules(options);
  if (chosen.length === 0) {
    return `no rule called "${options.id}" — mds rules lists them all\n`;
  }
  if (options.markdown === true) return asMarkdown(chosen);

  const color = options.color ?? true;
  if (chosen.length === 1 || options.id !== undefined) {
    return chosen
      .map((rule) =>
        [
          `${bold(rule.id, color)}  ${dim(rule.target, color)}`,
          "",
          wrap(rule.title, 78, "  "),
          "",
          wrap(rule.why, 78, "  "),
          "",
          wrap(`Instead: ${rule.instead}`, 78, "  "),
          "",
        ].join("\n"),
      )
      .join("\n");
  }

  const width = Math.max(...chosen.map((rule) => rule.id.length));
  return (
    chosen
      .map((rule) => `  ${bold(rule.id.padEnd(width), color)}  ${rule.title} ${dim(`(${rule.target})`, color)}`)
      .join("\n") + `\n\n${dim("mds rules <id> for the reasoning, --markdown for all of it", color)}\n`
  );
}
